### ISSUE TITLE
glow-on-hover

### ISSUE THREAD

**Issue by deltecacarrasco** [virtualitems/javascript-toolkit#14]
```css
.glow-on-hover {
  font-size: 16px;
  font-weight: 600;
  line-height: normal;
  min-height: 40px;
  min-width: 0;
  padding: 8px 16px;
  border: none;
  outline: none;
  color: #fff;
  background: #111;
  cursor: pointer;
  position: relative;
  z-index: 0;
  border-radius: 10px;
}
.glow-on-hover:before {
  content: "";
  background: linear-gradient(45deg, red, #ff7300, #fffb00, #48ff00, #00ffd5, #002bff, #7a00ff, #ff00c8, red);
  position: absolute;
  top: -2px;
  left: -2px;
  background-size: 400%;
  z-index: -1;
  filter: blur(5px);
  width: calc(100% + 4px);
  height: calc(100% + 4px);
  animation: glowing 20s linear infinite;
  opacity: 0;
  transition: opacity 0.3s ease-in-out;
  border-radius: 10px;
}
.glow-on-hover:active:after {
  transform: scale(0.95);
}
.glow-on-hover:hover:before {
  opacity: 1;
}
.glow-on-hover:after {
  z-index: -1;
  content: "";
  position: absolute;
  width: 100%;
  height: 100%;
  background: #111;
  left: 0;
  top: 0;
  border-radius: 10px;
}
.glow-on-hover:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
@keyframes glowing {
  0% {
      background-position: 0 0;
  }
  50% {
      background-position: 400% 0;
  }
  to {
      background-position: 0 0;
  }
}
```
